name: first-workflow
on: [workflow_dispatch]
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: greeter
        run: echo "hello my friend"
      - name: multiline
        run: |
          echo "Hi im line one"
          echo "Hi im line two"
